name: hello-world-sample

on: push

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      -name: check out repository code
       uses: actions/checkout@v4
      -runs: echo "$(cat hello_world.txt)"
